name: MATLAB Hello World

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  matlab-hello-world:
    runs-on: windows-2025
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2

      - name: Run hello.m using MATLAB Action
        uses: matlab-actions/run-command@v2
        with:
          command: hello